apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fagprove-backend
  namespace: laerlinger
spec:
  ingresses:
    - https://fagprove-backend.intern.dev.nav.no
  port: 8080
  ttl: 3h # Time before clean-up
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi